### ISSUE TITLE
about the cpu

### ISSUE THREAD

**Issue by dlutjwh** [PepperlFuchs/pf_lidar_ros_driver#113]
i transplant the code to ros2 and run successfully. with the main branch, i set 15Hz, but the average cpu is 7%(single core), comparing with  https://github.com/dillenberger/pepperl_fuchs,whose cpu is about 3%, on the same robot。are there any optimized point for cpu? thanks。

**Comment by ipa-hsd** [comment]
> i transplant the code to ros2 and run successfully

What do you mean? Were you able to run the ROS 2 version?

**Comment by dlutjwh** [comment]
yes, the origin code of branch ros2 canot  run,so i changed some code. now it can run on ros2。thanks sincerely。but the cpu is a little higher than https://github.com/dillenberger/pepperl_fuchs](https://github.com/dillenberger/pepperl_fuchs, which we also translant to ros2。maybe the new repository is also higher on ros1, where i have not tested. so what is the cpu of r2000 on ros1 with single core?

**Comment by ipa-hsd** [comment]
> yes, the origin code of branch ros2 canot run,so i changed some code. now it can run on ros2

Do you mean you made changes to https://github.com/PepperlFuchs/pf_lidar_ros_driver/tree/porting-ros2 ? Can you create a pull request to the `porting-ros2` branch so that I can take a look?

**Comment by dlutjwh** [comment]
sure,but now there are some problems with the laser data，after i solve it，i will try to create a pull request.

**Comment by ipa-hsd** [comment]
you can create a PR with "WIP" (work-in-progress) in the title. I can help with solving the problems with the laser data.

**Comment by dlutjwh** [comment]
i have create a PR，but there is some error with the data.   https://github.com/PepperlFuchs/pf_lidar_ros_driver/pull/114
