### ISSUE TITLE
wrong or missiong data  under high load

### ISSUE THREAD

**Issue by dlutjwh** [PepperlFuchs/pf_lidar_ros_driver#115]
when there are many other nodes started, the driver return a packet (0,0) points sometimes, which did not occur when only starting the r2000 driver. which was mentioned in https://github.com/PepperlFuchs/pf_lidar_ros_driver/pull/114, is it because UDP protocol?

**Comment by ipa-hsd** [comment]
> when there are many other nodes started, the driver return a packet (0,0) points sometimes

Does this happen also with ROS 1 version?

**Comment by ipa-hsd** [comment]
@dlutjwh I have updated https://github.com/PepperlFuchs/pf_lidar_ros_driver/pull/83. Could you please try again?

**Comment by ipa-hsd** [comment]
@dlutjwh are still facing the issue? Please re-open the issue if it still persists.
