### ISSUE TITLE
Reconnictivity issue

### ISSUE THREAD

**Issue by jadhm** [PepperlFuchs/pf_lidar_ros_driver#38]
Hi, 

The the node reconnects once the connection is lost with the scanner but the node doesn't keep trying to reconnect. In other words, if the connection was lost for a particular time the node raises an errors and it doesn't recover at all which means that the re-connectivity is not robust. Would you please look at this problem because the node should always keep trying to reconnect. 

Regards,
Jad

**Comment by ipa-hsd** [comment]
Yes I am aware of this and added an `enhancement` label to the issue.

**Comment by jadhm** [comment]
@ipa-hsd  Hi ! Any updates about this issue ?

**Comment by ptruka** [comment]
@jadhm Hi, this enhancement will be included in the next major version.

**Comment by ipa-hsd** [comment]
https://github.com/PepperlFuchs/pf_lidar_ros_driver/pull/81 has been merged
