### ISSUE TITLE
config.watchdog is always true

### ISSUE THREAD

**Issue by wsaihopfsg** [PepperlFuchs/pf_lidar_ros_driver#45]
In the virtual function `get_scanoutput_config` in `pfsdp_protocol.hpp`, the `json_keys` for "watchdog" is missing during the invocation of `get_request`, resulting in `config.watchdog` being always true.

Original code:
https://github.com/PepperlFuchs/ROS_driver/blob/80c423ad038d2ff197bd81588ad40ee3f3cd56e5/pf_driver/include/pf_driver/pf/pfsdp_protocol.hpp#L385

New code:
```
auto resp = get_request("get_scanoutput_config", {"start_angle", "packet_type", "watchdogtimeout", "skip_scans", "watchdog"}, { KV("handle", handle) });
```

**Comment by ipa-hsd** [comment]
Solved in https://github.com/PepperlFuchs/pf_lidar_ros_driver/pull/46
