### ISSUE TITLE
Is there a driver for ros2? Thanks!

### ISSUE THREAD

**Issue by Zhaohuanfeng** [PepperlFuchs/pf_lidar_ros_driver#61]
Is there a driver for ros2? Thanks!

**Comment by ptruka** [comment]
Not at the moment. We have just started sifting through the effort of a ros2 porting.

**Comment by iLanceS** [comment]
> @iLanceS we are about to start a new project which includes a ROS2 version.

@ipa-hsd
I have ported an [old version](https://github.com/dillenberger/pepperl_fuchs.git ) for ros2,but it  doesn't work well,some times it give me a mistake position,  It's spinning by a random period。

So，When do you start?

**Comment by andrestoga** [comment]
@ipa-hsd how is the project going? any updates on the ROS2 version?

**Comment by PepperlFuchs** [comment]
Hello,
The ROS2 driver will be there in Q2.
BR
