### ISSUE TITLE
frame_id of the LaserScanMsg should be configurable

### ISSUE THREAD

**Issue by HenrikasRS** [PepperlFuchs/pf_lidar_ros_driver#76]
ScanPublisherR2000 and ScanPublisherR2300 constructors are called (in pf_interface.cpp:186) with hardcoded parameters frame_id (set value "scanner") and topic (set value "/scan"). It should be configurable because sometimes in ros frame structure there's more than one laser scanner and they need unique frame_id's. Similar problem with the topic parameter, but this one can be fixed easier by remapping in launch file.

**Comment by ipa-hsd** [comment]
[This PR](https://github.com/PepperlFuchs/pf_lidar_ros_driver/pull/75) makes it configurable. You should be able to set the values in yaml file: https://github.com/PepperlFuchs/pf_lidar_ros_driver/blob/bb2c993f8a2d738b56fd9fa2d76f8a8607b0f0f0/pf_driver/config/r2000_params.yaml#L9

**Comment by ipa-hsd** [comment]
https://github.com/PepperlFuchs/pf_lidar_ros_driver/pull/75 is merged
