### ISSUE TITLE
ROS2 support

### ISSUE THREAD

**Issue by wawanbreton** [PepperlFuchs/pf_lidar_ros_driver#80]
Hi,
I'm using an R2000 lidar with ROS2, currently using a bridge from the ROS1 driver.
I will now have a need not to use the bridge anymore, and having only ROS2 nodes.
Is there a work in progress for ROS2 porting ? If not, I will start forking the repository and do it myself, but I just wanted to be sure nobody is alreay working on it.

**Comment by wawanbreton** [comment]
Thanks for the feedback.
I just pushed a basically working version on my branch. I was about to start doing some refactoring, but it seems useless if you are up to it. You can take a look at it if needed on some points.
I have been struggling about the deserialization of the header, since it is a bit more complicated (impossible ?) with ROS2, so I did a quick-and-dirty implementation. I'm curious to see how you will handle it :)
Of course I would be happy to test your implementation if you need to, however I only have R2000 LIDARs.

**Comment by ipa-hsd** [comment]
I am guessing this is the branch: https://github.com/wawanbreton/pf_lidar_ros_driver/tree/porting-ros2

Thanks for the initial work! I have created a PR here: https://github.com/PepperlFuchs/pf_lidar_ros_driver/pull/82
I will push more commits to it

**Comment by wawanbreton** [comment]
Ok, nice ! I think it requires some refactoring : I had to reorganize the initialization as in ROS2 you can't read the parameters before the node is created, so I did things that are not very clean. It works for me yet so I can use my LIDAR, but feel free to break what I did !

**Comment by ipa-hsd** [comment]
sure :) Porting of the `package.xml` and `CMakeLists.txt` is already good contribution.

**Comment by ipa-hsd** [comment]
https://github.com/PepperlFuchs/pf_lidar_ros_driver/pull/82 has been closed and the work is being continued on https://github.com/PepperlFuchs/pf_lidar_ros_driver/pull/83.

**Comment by shaoxiang** [comment]
Is there a time schedule for ROS2 support? Thanks.

**Comment by chenwu-cc** [comment]
> ROS2 支持有时间表吗？谢谢。

Can you use the porting ROS2 version normally? We urgently need the ROS2 version driver

**Comment by andrewTianxiaolu** [comment]
Hi there. I just tried the porting-ros2 branch on Ubuntu22/ros2 humble, and I met an error when I build the pf_driver. The error is no matching function for call to ‘rclcpp::Duration::Duration(double)’. I have already installed the rosdep before building the source code. 
![倍加福编译问题](https://github.com/PepperlFuchs/pf_lidar_ros_driver/assets/91037369/66b7a36a-68fd-4f25-84a0-a62fc5cc5462)
Does anybody have met the same problem like it?

**Comment by ipa-hsd** [comment]
> Hi there. I just tried the porting-ros2 branch on Ubuntu22/ros2 humble, and I met an error when I build the pf_driver. The error is no matching function for call to ‘rclcpp::Duration::Duration(double)’. I have already installed the rosdep before building the source code. ![倍加福编译问题](https://user-images.githubusercontent.com/91037369/250021762-66b7a36a-68fd-4f25-84a0-a62fc5cc5462.png) Does anybody have met the same problem like it?

Thanks for testing it on Humble. The driver has been tested only on foxy and galactic. I will take a look at the Humble api and make changes in the coming days.

**Comment by shaoxiang** [comment]
> > ROS2 支持有时间表吗？谢谢。
> 
> Can you use the porting ROS2 version normally? We urgently need the ROS2 version driver

It can already be run on ROS2 foxy version.

**Comment by PGotzmann** [comment]
Thanks for porting this to ROS2. Really looking forward to this release.
Since both foxy and galactic are already end of life for quiet some time now I still need to ask if you are also planing to release this on Humble and if so when we can expect such a release.

**Comment by ipa-hsd** [comment]
@PGotzmann thanks for your interest. There was a small change required for humble. This week we fixed few bugs related to setting (changing) parameters at runtime. Next week we have planned an extensive test for Foxy, Galactic and Humble.

**Comment by ipa-hsd** [comment]
@andrewTianxiaolu said:
> Hi there. I just tried the porting-ros2 branch on Ubuntu22/ros2 humble, and I met an error when I build the pf_driver. The error is no matching function for call to ‘rclcpp::Duration::Duration(double)’. I have already installed the rosdep before building the source code. ![倍加福编译问题](https://user-images.githubusercontent.com/91037369/250021762-66b7a36a-68fd-4f25-84a0-a62fc5cc5462.png) Does anybody have met the same problem like it?

https://github.com/PepperlFuchs/pf_lidar_ros_driver/pull/83/commits/46ca683de303f86254dd90e7513f8ae6b385bb1d should fix the error. 

Another "fix" that might be needed is mentioned here: https://github.com/open-source-parsers/jsoncpp/issues/1356

**Comment by hsd-dev** [comment]
As mentioned in https://github.com/PepperlFuchs/pf_lidar_ros_driver/pull/83#issuecomment-1815977173, the ROS 2 version for foxy, galactic, humble and iron has been moved to a new repo: https://github.com/PepperlFuchs/pf_lidar_ros2_driver. The initial testing is done. Please test the driver and create issues in the new repo.
