### ISSUE TITLE
How to configure angular fov for r2000?

### ISSUE THREAD

**Issue by BIRL-xu** [PepperlFuchs/pf_lidar_ros_driver#88]
I can connect to r2000 normally, but I want to specify a angular fov, e.g. 180 degrees. I set the start_angle to -1.57, the topic echo shows the angle_min is -1.57, but angle_max is 4.71(2PI-start_angle).

**Comment by ipa-hsd** [comment]
I think we can close this issue. @BIRL-xu please feel free to reopen if your question isn't answered.
