### ISSUE TITLE
Config  "packet_type" qeustion

### ISSUE THREAD

**Issue by guomengnick** [PepperlFuchs/pf_lidar_ros_driver#89]
Hi,
i want to know what is different
packet_type A and B.

thanks.

**Comment by ipa-hsd** [comment]
You can find the information in the R2000's ethernet protocol: https://files.pepperl-fuchs.com/webcat/navi/productInfo/doct/doct3469f.pdf?v=20201005101009 (section "3.4 Transmission of scan data")
