### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by MichaelGrupp** [PepperlFuchs/pf_lidar_ros_driver#92]
Hi,

I just wanted to ask what your schedule for a new release looks like. The latest release in the ROS Noetic distro is 1.2.0, and since then there have been quite a number of improvements committed to this repo, which probably would also benefit the users who install the package from the distro. Thanks in advance!

**Comment by ipa-hsd** [comment]
@ptruka will be back at office in 1st week of November I think. https://github.com/PepperlFuchs/pf_lidar_ros_driver/pull/86 is the last pending PR to be reviewed before the release.

**Comment by Arthav24** [comment]
Hey, Just curious any timeline for release?

**Comment by RainerKuemmerle** [comment]
The mentioned PR is merged. Any update / plans on a next release. Thanks.
