### ISSUE TITLE
driver params

### ISSUE THREAD

**Issue by dlutjwh** [PepperlFuchs/pf_lidar_ros_driver#96]
hi,
in this version :https://github.com/dillenberger/pepperl_fuchs, we can use the param scan_frequency, but in the new rep, we cannot find the param scan_frequency. how can we use it?

sincerely thanks

**Comment by ipa-hsd** [comment]
`scan_frequency` is a dynamic reconfigure parameter See: https://github.com/PepperlFuchs/pf_lidar_ros_driver/blob/main/pf_driver/cfg/PFDriverR2000.cfg#L19 and https://github.com/PepperlFuchs/pf_lidar_ros_driver/blob/main/pf_driver/cfg/PFDriverR2300.cfg#L39.  For details on how to use dynamic reconfigure, refer to http://wiki.ros.org/dynamic_reconfigure
